name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build: linux-x32-gnu
            os: ubuntu-latest
            target: i686-unknown-linux-gnu
          - build: linux-x64-gnu
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: macos-x64
            os: macOS-latest
            target: x86_64-apple-darwin
          - build: windows-x32-msvc
            os: windows-latest
            target: i686-pc-windows-msvc
          - build: windows-x64-msvc
            os: windows-latest
            target: x86_64-pc-windows-msvc
          - build: windows-x32-gnu
            os: windows-latest
            target: i686-pc-windows-gnu
          - build: windowa-x64-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu
          
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Pack archive
        continue-on-error: true
        run: tar cfvz bunnyfetch.tar.gz target/release/bunnyfetch target/release/bunnyfetch.exe README.md LICENSE
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bunnyfetch.tar.gz
          asset_name: bunnyfetch-${{ matrix.build }}.tar.gz
          tag: ${{ github.ref }}